title: MediPulse
description: "Hospital Finder"
owner_name: Gavin Copley
github_username: GavinCopley
github_repo: "MediPulse"
baseurl: "/MediPulse"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-jupyter-notebook
header_pages:
  - navigation/authentication/MLhospital.md
  - navigation/dataAnalytics.md

Server: https://medipulse.opencodingsociety.com/
Domain: https://medipulse.opencodingsociety.com/
Subdomain: https://medipulse.opencodingsociety.com/

